# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 20) do

  create_table "administrators", :force => true do |t|
    t.column "email",       :string,   :limit => 64, :default => "", :null => false
    t.column "pass",        :string,   :limit => 40, :default => "", :null => false
    t.column "salt",        :string,   :limit => 10, :default => "", :null => false
    t.column "created_at",  :datetime,                               :null => false
    t.column "modified_at", :datetime,                               :null => false
  end

  create_table "pages", :force => true do |t|
    t.column "title",       :string,   :limit => 128, :default => "", :null => false
    t.column "name",        :string,   :limit => 128, :default => "", :null => false
    t.column "text",        :text
    t.column "created_at",  :datetime,                                :null => false
    t.column "modified_at", :datetime
  end

  create_table "registrants", :force => true do |t|
    t.column "student_id",        :integer
    t.column "workshop_id",       :integer
    t.column "payment_submitted", :date
    t.column "payment_received",  :date
  end

  create_table "students", :force => true do |t|
    t.column "first_name",        :string,   :limit => 64,  :default => "", :null => false
    t.column "last_name",         :string,   :limit => 64,  :default => "", :null => false
    t.column "email",             :string,   :limit => 128, :default => "", :null => false
    t.column "address1",          :string,   :limit => 128, :default => "", :null => false
    t.column "address2",          :string,   :limit => 128
    t.column "city",              :string,   :limit => 128, :default => "", :null => false
    t.column "state",             :string,   :limit => 2,   :default => "", :null => false
    t.column "zip",               :string,   :limit => 9,   :default => "", :null => false
    t.column "phone",             :string,   :limit => 10
    t.column "ext",               :string,   :limit => 10
    t.column "created_at",        :datetime,                                :null => false
    t.column "modified_at",       :datetime
    t.column "pass",              :string,   :limit => 40,                  :null => false
    t.column "salt",              :string,   :limit => 10
    t.column "new_password",      :string,   :limit => 32
    t.column "new_password_date", :date
  end

  create_table "workshops", :force => true do |t|
    t.column "name",         :string,   :limit => 128, :default => "",    :null => false
    t.column "short_name",   :string,   :limit => 128, :default => "",    :null => false
    t.column "description",  :text,                                       :null => false
    t.column "cutoff_date",  :date,                                       :null => false
    t.column "start_date",   :date,                                       :null => false
    t.column "end_date",     :date,                                       :null => false
    t.column "max_students", :integer
    t.column "cost",         :float
    t.column "created_at",   :datetime,                                   :null => false
    t.column "modified_at",  :datetime
    t.column "active",       :boolean,                 :default => false
    t.column "thumbnail",    :string
    t.column "short_desc",   :text
    t.column "full",         :boolean,                 :default => false
    t.column "ancestor_id",  :integer
  end

end
